// lib/exportPdf.ts
// Export the full agent chat as a PDF using jsPDF + html2canvas.
// Charts are captured as rasterised images. Text is embedded as-is.
// Called from AgentWidget with a ref to the chat container element.

export interface PdfMessage {
  role:      'user' | 'assistant';
  content:   string;
  createdAt: Date;
}

/**
 * Export the agent chat to a PDF.
 * @param containerEl  The DOM element wrapping all chat messages (used for html2canvas)
 * @param messages     The messages array (used as fallback text)
 * @param agentName    Name to show in the PDF header
 */
export async function exportChatToPdf(
  containerEl: HTMLElement,
  messages:    PdfMessage[],
  agentName:   string = 'FundsAgent'
): Promise<void> {
  // Dynamic imports — avoids SSR issues (jspdf and html2canvas are client-only)
  const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
    import('jspdf'),
    import('html2canvas'),
  ]);

  const dateStr = new Date().toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  // ── Capture chat container as canvas ────────────────────────────────────────
  const canvas = await html2canvas(containerEl, {
    scale:           2,          // 2x for retina clarity
    useCORS:         true,
    backgroundColor: '#ffffff',
    logging:         false,
    windowWidth:     containerEl.scrollWidth,
    windowHeight:    containerEl.scrollHeight,
  });

  const imgData   = canvas.toDataURL('image/png');
  const imgWidth  = canvas.width;
  const imgHeight = canvas.height;

  // ── Build PDF ────────────────────────────────────────────────────────────────
  // A4 page: 210mm × 297mm. We set orientation to portrait.
  const pdf       = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW     = pdf.internal.pageSize.getWidth();  // 210mm
  const pageH     = pdf.internal.pageSize.getHeight(); // 297mm
  const margin    = 12; // mm
  const usableW   = pageW - margin * 2;
  const usableH   = pageH - margin * 2;

  // ── Page 1: Header ──────────────────────────────────────────────────────────
  pdf.setFillColor(79, 70, 229); // indigo-600
  pdf.rect(0, 0, pageW, 18, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(13);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`${agentName} — Chat Export`, margin, 12);

  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.text(dateStr, pageW - margin - pdf.getTextWidth(dateStr), 12);

  // Reset text colour for body
  pdf.setTextColor(30, 30, 30);

  // ── Tile the captured image across pages ────────────────────────────────────
  // Scale factor: fit width to usableW
  const scale     = (usableW / imgWidth) * (canvas.width / canvas.width); // = usableW / imgWidth (in px/mm)
  const scaledW   = usableW; // mm
  const scaledH   = (imgHeight / imgWidth) * usableW; // mm, proportional

  // Start below header on page 1
  const startY    = 22; // mm — below header
  const firstPageH = pageH - startY - margin;

  let remainingH  = scaledH;
  let srcOffsetY  = 0; // in mm within the scaled image

  // Page 1 slice
  const sliceH1 = Math.min(firstPageH, remainingH);
  if (sliceH1 > 0) {
    // Crop the canvas to the first slice
    const slicePx1 = Math.round((sliceH1 / scaledH) * imgHeight);
    const slice1   = cropCanvas(canvas, 0, srcOffsetY, imgWidth, slicePx1);
    pdf.addImage(slice1.toDataURL('image/png'), 'PNG', margin, startY, scaledW, sliceH1);
    srcOffsetY += slicePx1;
    remainingH -= sliceH1;
  }

  // Subsequent pages
  while (remainingH > 0) {
    pdf.addPage();

    // Small header stripe on continuation pages
    pdf.setFillColor(79, 70, 229);
    pdf.rect(0, 0, pageW, 8, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(7);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`${agentName} — continued`, margin, 5.5);
    pdf.setTextColor(30, 30, 30);

    const sliceH = Math.min(usableH, remainingH);
    const slicePx = Math.round((sliceH / scaledH) * imgHeight);
    const slice   = cropCanvas(canvas, 0, srcOffsetY, imgWidth, slicePx);
    pdf.addImage(slice.toDataURL('image/png'), 'PNG', margin, 10, scaledW, sliceH);
    srcOffsetY += slicePx;
    remainingH -= sliceH;
  }

  // Footer on last page
  const totalPages = (pdf as any).internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    pdf.setPage(p);
    pdf.setFontSize(7);
    pdf.setTextColor(150, 150, 150);
    pdf.setFont('helvetica', 'normal');
    const footerText = `Page ${p} of ${totalPages} · Generated by ${agentName} · ${dateStr}`;
    pdf.text(footerText, pageW / 2, pageH - 5, { align: 'center' });
  }

  // ── Save ─────────────────────────────────────────────────────────────────────
  const fileName = `fundsagent-chat-${new Date().toISOString().slice(0, 10)}.pdf`;
  pdf.save(fileName);
}

// ── Utility: crop a canvas vertically ────────────────────────────────────────

function cropCanvas(
  src:    HTMLCanvasElement,
  x:      number,
  y:      number,
  w:      number,
  h:      number
): HTMLCanvasElement {
  const cropped = document.createElement('canvas');
  cropped.width  = w;
  cropped.height = h;
  const ctx = cropped.getContext('2d')!;
  ctx.drawImage(src, x, y, w, h, 0, 0, w, h);
  return cropped;
}
